# Generated by Django 3.1.3 on 2020-11-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalModel',
            fields=[
                ('localId', models.AutoField(db_column='local_id', primary_key=True, serialize=False, unique=True)),
                ('localNomb', models.CharField(db_column='local_nomb', max_length=50)),
                ('localDir', models.CharField(db_column='local_dir', max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 't_local',
            },
        ),
    ]
