# Generated by Django 3.1.3 on 2020-11-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCanchaModel',
            fields=[
                ('tipoCanchaId', models.AutoField(db_column='tc_id', primary_key=True, serialize=False, unique=True)),
                ('tipoCanchaDesc', models.CharField(db_column='tc_desc', max_length=40)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 't_tipocancha',
            },
        ),
        migrations.CreateModel(
            name='TipoClienteModel',
            fields=[
                ('tipoClienteId', models.AutoField(db_column='tc_id', primary_key=True, serialize=False, unique=True)),
                ('tipoClientePrec', models.DecimalField(db_column='tc_prec', decimal_places=2, max_digits=5)),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='update_at')),
            ],
            options={
                'db_table': 't_tipocliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('clienteId', models.AutoField(db_column='cliente_id', primary_key=True, serialize=False, unique=True)),
                ('clienteNombre', models.CharField(db_column='cliente_nombre', max_length=40)),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('tipoClienteId', models.ForeignKey(db_column='tc_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientesTipo', to='administracion.tipoclientemodel')),
            ],
            options={
                'db_table': 't_cliente',
            },
        ),
        migrations.CreateModel(
            name='CanchaModel',
            fields=[
                ('canchaId', models.AutoField(db_column='cancha_id', primary_key=True, serialize=False, unique=True)),
                ('canchaNomb', models.CharField(db_column='cancha_nom', max_length=40)),
                ('canchaPrecio', models.DecimalField(db_column='cancha_prec', decimal_places=2, max_digits=5)),
                ('canchaEstado', models.BooleanField(db_column='cancha_est', default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('localId', models.ForeignKey(db_column='local_id', on_delete=django.db.models.deletion.PROTECT, related_name='canchasLocal', to='administracion.localmodel')),
                ('tipoCanchaId', models.ForeignKey(db_column='tc_id', on_delete=django.db.models.deletion.PROTECT, related_name='canchasTipoCancha', to='administracion.tipocanchamodel')),
            ],
            options={
                'db_table': 't_cancha',
            },
        ),
    ]
