# Generated by Django 3.1.3 on 2020-11-15 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_canchamodel_clientemodel_tipocanchamodel_tipoclientemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroModel',
            fields=[
                ('registroId', models.AutoField(db_column='reg_id', primary_key=True, serialize=False, unique=True)),
                ('registroPrecFinal', models.DecimalField(db_column='reg_precfin', decimal_places=2, max_digits=5)),
                ('registroFechIni', models.DateTimeField(db_column='reg_fechin')),
                ('registroFechFin', models.DateTimeField(db_column='reg_fechfin')),
                ('canchaId', models.ForeignKey(db_column='cancha_id', on_delete=django.db.models.deletion.PROTECT, related_name='registrosCancha', to='administracion.canchamodel')),
                ('clienteId', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='registrosCliente', to='administracion.clientemodel')),
            ],
            options={
                'db_table': 't_registro',
            },
        ),
    ]
